name: CAC-TAT regression with Lunatic test framework
on:
  push:
    branches: [ main ]
  schedule:
    # This runs every sunday at 00:00 (Midnight) UTC
    - cron: '0 0 * * 0'
jobs:
  lunatic-web-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: leafo/gh-actions-lua@v13
      with:
        luaVersion: "5.2.0"
    - uses: leafo/gh-actions-luarocks@v6
    - name: Run Lua test
      run: lua -v
    - name: Run a regression
      env:
        # env vars to use at step
        LUNATIC: "yes"
      run: |
        luarocks install lunatic
        echo "bin"
        ls -a .luarocks/bin
        echo "etc"
        ls -a .luarocks/etc
        echo "lib"
        ls -a .luarocks/lib
        echo "share"
        ls -a .luarocks/share
        #cd regression
        #lua web_regression.lua
    
