name: CAC-TAT regression with Lunatic test framework
on:
  push:
    branches: [ main ]
  schedule:
    # This runs every sunday at 00:00 (Midnight) UTC
    - cron: '0 0 * * 0'
jobs:
  lunatic-web-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Getting Lua
      uses: leafo/gh-actions-lua@v13
      with:
        luaVersion: "5.2.0"
    - name: Getting Luarocks
      uses: leafo/gh-actions-luarocks@v6
    - name: Run Lua test
      run: lua -v
    - name: Run a regression
      env:
        # env vars to use at step
        LUNATIC: "yes"
      run: |
        xvfb-run firefox -headless &
        luarocks install lunatic
        cd regression
        lua web_regression.lua
